// netlify/functions/ai.js
export default async (req) => {
  try {
    const { text } = await req.json();
    if (!text) {
      return new Response(JSON.stringify({ error: "Missing text" }), { status: 400 });
    }

    // Use your OpenAI API key stored in Netlify
    const apiKey = process.env.OPENAI_API_KEY;

    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: [
          { role: "system", content: "You are a Bible study companion. Provide a summary, key themes, and a reflection question based on the passage." },
          { role: "user", content: text }
        ]
      })
    });

    const data = await response.json();

    // Extract the assistant’s reply
    const aiText = data.choices?.[0]?.message?.content || "No response from AI";

    // For now, just return the AI text under 'summary'
    return new Response(JSON.stringify({
      summary: aiText,
      themes: ["Generated by AI"],
      question: "What is one way you can apply this passage today?"
    }), {
      headers: { "Content-Type": "application/json" },
      status: 200
    });

  } catch (e) {
    return new Response(JSON.stringify({ error: "Server error" }), { status: 500 });
  }
};


